-- DB2 CLP execute this script file:
-- db2 -vtd@ -f E:\sandboxes_my\Java_Workspace\HibernateDemo\sql\db2_table_ddl.sql -z C:\out.txt

-- db_type:		DB2
-- db_name:		sample
-- table_name:	sys_user
create table sys_user (
	user_id bigint generated by default as identity(start with 1, increment by 1, cache 20) not null,
	name varchar(32),
	password varchar(200),
	type smallint
)@
-- table_name:	sys_department
create table sys_department (
	dept_id bigint generated by default as identity(start with 1, increment by 1, cache 20) not null,
	name varchar(100),
	parent_id bigint,
	manager_id bigint
)@
-- table_name:	collection
create table collection (
	id bigint,
	name varchar(32)
)@
-- table_name:	t_lists
create table t_lists(
	list_id bigint,
	list_index bigint,
	list_value varchar(100)
)@
-- table_name:	t_sets
create table t_sets(
	set_id bigint,
	set_value varchar(100)
)@
-- table_name:	t_maps
create table t_maps(
	map_id bigint,
	map_key varchar(32)
	map_value varchar(100)
)@
-- table_name:	t_arrays
create table t_arrays(
	list_id bigint,
	list_index bigint,
	list_value varchar(100)
)@